### ISSUE TITLE
Use Progenitor as the client generator

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/oxide.rs-old#81]
## Background

Currently this client is generated through a custom generator found at [generator/](https://github.com/oxidecomputer/oxide.rs/tree/main/generator). 

As time progresses, this client veers towards having customisations specific to the [Oxide CLI](https://github.com/oxidecomputer/cli), and away from how the rest of the Rust clients are generated at this company. This can cause the following:

- The generator in this repo becomes more difficult to maintain as time passes by.
- This client does not benefit from any upgrades and features made to Progenitor.
- Contributions from non-maintainers of this repo is more difficult.
- The feedback loop from the developers of external facing clients to the developers of the user API is hindered.

## Expected outcome

This client should be generated by Progenitor.

## Plan of attack

- [ ] Find which customisations can be ported to Progenitor.
- [ ] Find which customisations can be ported to openapi-lint.
- [ ] Find which customisations can be ported to the CLI.
- [ ] Find which customisations we can compromise on.
- [ ] Use Progenitor to generate this client 🎉

**Comment by ahl** [comment]
This is great! Thanks for working on it.

I'm pretty sure we'll want to decide on an answer to https://github.com/oxidecomputer/progenitor/issues/23.

The examples that were are added to the openapi json were pretty cool. What do we think about a mode where progenitor can emit json patch output to provide a mechanism to drop them in?

**Comment by karencfv** [comment]
Ah yeah! I'd seen that issue, I'll subscribe to it and give my 2 cents.

About the examples/code snippets, @david-crespo had a really good idea on how to [generate them](https://github.com/oxidecomputer/docs/issues/235) directly from the docs repo without having to modify the API spec. That said, I think leveraging tags would really help with the docs generation to have a clear place to retrieve information from, instead of retrieving the information from the summary or other fields.

**Comment by karencfv** [comment]
Progress can be followed here https://github.com/oxidecomputer/oxide-sdk-rust

**Comment by karencfv** [comment]
Closing as this is now tracked in https://github.com/oxidecomputer/oxide-sdk-and-cli

**Comment by jayvdb** [comment]
Just noting that https://github.com/oxidecomputer/oxide-sdk-rust and https://github.com/oxidecomputer/oxide-sdk-and-cli are not visible to the public.
